apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting
    spec:
      containers:
        - name: accounting
          image: djans/accounting:2a41dae22ba695452b78e76d7db47690d723bd50
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/accounting
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password


