apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting
    spec:
      containers:
        - name: accounting
          image: djans/accounting:e51fbfd784e127a34c71ce22d291070908aeb6eb
          ports:
            - containerPort: 80
          env:
            - name: APP_BOOTSTRAP_ADMIN_EMAIL
              value: djans@cogitosum.com
            - name: APP_BOOTSTRAP_ADMIN_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/accounting
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password


